= Pack-Riemann

Package up Riemann and Riemann-dash into an AMI using Packer and provision using Terraform.

== Build the Packer AMI.

```
packer build -var 'riemann_version=0.2.12' riemann.json
```

== Deploy using Terraform

See the `sample.tf` for a straightforward Terraform configuration to provision Riemann. Terraform also has a https://www.terraform.io/intro/[getting started guide].

One option is to clone this repository into a working subdirectory of your project to start using it. You could also refer to the module directly from Git:

....
module "riemann" {
  source = "github.com/juxt/pack-riemann//modules/riemann?ref=0.2.0"
  # Declare variable inputs
  # ...
}
....

To use this module you need to provide the relevant variables that are declared at the top of `sample.tf`, you can do so either from the command line or from a tf.vars file. Assuming you went ahead and supplied the variables in a `dev.tfvars` file, then the Terraform commands to plan and to subsequently execute
provisioning would be:

First export where your private key is that matches the `key_path` variable (or you'll be asked to type it in). The provisioner needs this to upload the Riemann config file.

....
export TF_VAR_key_path=<where is it?>
....


Get the module ready:

....
terraform get
....

Make the Terraform plan

....
terraform plan -var-file=dev.tfvars -out proposed.plan
....

Execute the plan:

....
terraform apply proposed.plan
....

== Requirements

Packer and Terraform 0.8.
